import { useState } from 'react';
import { BlueSeal } from '../../components/BlueSeal';
import { FloatingShapes } from '../../components/FloatingShapes';
import { MobileFrame } from '../../components/MobileFrame';

export function ForgotPasswordFlow({ onBack }: { onBack: () => void }) {
  const [email, setEmail] = useState(''); const [next, setNext] = useState(false); const [sent, setSent] = useState(false); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState('');
  const valid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  async function send() { if (!valid) return setError('请输入正确的邮箱地址'); setError(''); try { const response = await fetch('/api/auth/password-reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email }) }); if (!response.ok) throw new Error(); const result = await response.json() as { resetUrl?: string }; if (result.resetUrl) localStorage.setItem('temlore.reset.preview', result.resetUrl); setSent(true); } catch { setError('邮件发送失败，请确认本地服务器和 Resend 配置已启动'); } }
  function save() { if (password.length < 6) return setError('新密码至少需要 6 位'); if (password !== confirm) return setError('两次输入的密码不一致'); onBack(); }
  return <MobileFrame showTime={false} className="auth-screen forgot-screen"><FloatingShapes /><header className="auth-brand"><button className="auth-back" onClick={onBack}>←</button><div>Teml<BlueSeal variant="logo" />re</div><span>Sign</span></header><section className="auth-heading"><small>{next ? 'SET A NEW PASSWORD' : 'ACCOUNT RECOVERY'}</small><h1>{next ? 'NEW PASSWORD' : 'FORGOT PASSWORD'}</h1><em>{next ? '设置新的登录密码' : '通过邮箱找回你的时间书桌'}</em></section>{!next ? <><div className="auth-field auth-phone forgot-email"><span className="user-label">邮箱</span><input aria-label="找回邮箱" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="邮箱地址" /></div>{sent ? <div className="reset-sent"><b>重置链接已发送</b><span>请检查 {email} 的收件箱</span><button onClick={() => setNext(true)}>打开邮件中的重置链接</button></div> : <button className="auth-submit forgot-submit" onClick={send}>→</button>}</> : <><div className="auth-field auth-phone forgot-email"><span className="user-label">新密码</span><input aria-label="新密码" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="至少 6 位" /></div><div className="auth-field auth-code forgot-confirm"><input aria-label="确认密码" type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="再次输入密码" /></div><button className="auth-submit forgot-submit" onClick={save}>→</button></>}{error && <p className="auth-error" role="alert">{error}</p>}</MobileFrame>;
}
